[package]
name = "argus"
version = "0.1.0"
edition = "2021"
authors = ["Wenxuan Shi <wenxuan.shi@northwestern.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
